AWSTemplateFormatVersion: 2010-09-09
Description: MyCloud buckets
Parameters:
  InstanceProfileName:
    Type: String
    Default: ''

Conditions:
  DoAddInstanceProfile: !Not [!Equals [!Ref InstanceProfileName, ""]]

Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !If
        - DoAddInstanceProfile
        - !Ref InstanceProfileName
        - !Ref AWS::NoValue
      ImageId: ami-0b59bfac6be064b78
      InstanceType: t2.micro
Outputs:
  Objects:
    Value: !Ref Instance
  StackName:
      Value: !Ref 'AWS::StackName'
  StackId:
      Value: !Ref 'AWS::StackId'
