AWSTemplateFormatVersion: 2010-09-09
Description: MyCloud buckets
Parameters:
  InstanceProfileName:
    Type: String
    Default: ''

  InstanceRole:
    Type: String
    Default: ''

Conditions:
  DoCreateProfile: !Not [!Equals [!Ref InstanceProfileName, ""]]

Resources:
  IAMProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Condition: DoCreateProfile
    Properties:
      InstanceProfileName: !Ref InstanceProfileName
      Roles:
        - !Ref InstanceRole

Outputs:
  profilename:
    Value: !If
      - DoCreateProfile
      - !Ref IAMProfile
      - ""
  StackName:
      Value: !Ref 'AWS::StackName'
  StackId:
      Value: !Ref 'AWS::StackId'
